---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: flux-01
  labels:
    app: podinfo
  annotations:
    fluxcd.io/automated: "true"
    anno1 : "val1"
    anno2 : "val2"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
      annotations:
        annop1 : "valp1"
        annop2 : "valp2"
    spec:
      initContainers:
      - name: init
        image: nidabasregistry.azurecr.io:latest
        command:
        - sleep
        - "1"
      containers:
      - name: podinfo-cap
        image: nidabasregistry.azurecr.io/hello-world
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 9233
            protocol: TCP
          - name: http-metrics
            containerPort: 9797
            protocol: TCP
          - name: grpc
            containerPort: 9999
            protocol: TCP
        command:
          - ./podinfo
          - --port=9233
          - --port-metrics=9797
          - --grpc-port=9999
          - --grpc-service-name=podinfo
          - --level=info
          - --random-delay=false
          - --random-error=false
        env:
          - name: PODINFO_UI_COLOR
            value: "#34577c"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: podinfo
      annotations:
        annod21 : "vald21"
        annod22 : "vald22"
    spec:
      containers:
      - name: podinfo
        image: nidabasregistry.azurecr.io/hello-world:latest
        ports:
        - containerPort: 3000
