apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: flux-01
  labels:
    app: podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
  - name: http
    port: 9234
    protocol: TCP
    targetPort: http
